before:
  hooks:
    - go mod tidy
builds:
  - id: repo-manager
    binary: repo-manager
    main: ./cmd/repo-manager
    ldflags:
      - -s
      - -w
      - -X main.version={{.Summary}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
dockers:
  - id: repo-manager
    goos: linux
    goarch: amd64
    ids:
      - repo-manager
    image_templates:
      - "kazhuravlev/repo-manager:latest"
      - "kazhuravlev/repo-manager:{{ .Tag }}"
      - "kazhuravlev/repo-manager:v{{ .Major }}"
      - "kazhuravlev/repo-manager:v{{ .Major }}.{{ .Minor }}"
    dockerfile: 'Dockerfile'
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
brews:
  - name: repo-manager
    goarm: "6"
    goamd64: v3
    tap:
      owner: kazhuravlev
      name: homebrew-repo-manager
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/kazhuravlev/repo-manager/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: kazhuravlev+goreleaserbot@fastmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/kazhuravlev/repo-manager"
    description: "Repo manager allows you to check repo dependencies."
    license: "MIT"
    test: |
      system "#{bin}/repo-manager help"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
