// Code generated by options-gen. DO NOT EDIT.
package repomgr

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	spec Spec,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)
	o.privateKey = "$HOME/.ssh/id_rsa"

	o.spec = spec

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithPrivateKey(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.privateKey = opt
	}
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("spec", _validate_Options_spec(o)))
	errs.Add(errors461e464ebed9.NewValidationError("privateKey", _validate_Options_privateKey(o)))
	return errs.AsError()
}

func _validate_Options_spec(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.spec, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `spec` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_privateKey(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.privateKey, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `privateKey` did not pass the test: %w", err)
	}
	return nil
}
